spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.145.26:3306/icourse
    username: icourseuser
    password: ztjztj120
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8081